### ISSUE TITLE
Strona główna

### ISSUE THREAD

**Issue by martab0** [mklimek1/my-docs#1]
Technical writers can make valuable contributions to open source projects by creating and maintaining documentation that helps developers and users understand how to use the software. A well-written and comprehensive documentation can make a significant difference in the success of an open source project. -> Technical writers can make valuable contributions to open source projects by creating and maintaining documentation that helps developers and users understand how to use the software. A well-written and comprehensive documentation makes a significant difference in the success of an open source project.

Nie warto osłabiać przekazu przez drugie "can".
Potrzebna jest króciutka definicja, czym są open source projects (tj. na czym polega koncepcja open software). Tę samą rolę spełni odsyłacz pod wystąpieniem 'open source projects' na stronie głównej do wiarygodnej strony definiującej open source, np. https://opensource.org/osd/.

**Comment by mklimek1** [comment]
Thanks ! Updated
