### ISSUE TITLE
Understand

### ISSUE THREAD

**Issue by martab0** [mklimek1/my-docs#10]
Rozdział traktuje o funkcji dokumentacji, więc powinien znaleźć się znacznie wcześniej. Informacje są ważne i potrzebne, ale proszę o uważne i krytyczne przeczytanie i streszczenie (znów niepokoi liczba wystąpień "can").
"It can also help developers to understand the software’s architecture, functionalities, and features. " - raczej nie, developerzy wiedzą, co piszą :-)
- dokumentacja dla developerów, żeby wiedzieli, jakie były przyjęte założenia, algorytmy itd. (-> debugowanie, testy)
- dokumentacja dla nowych developerów włączających się w projekt
- dokumentacja dla użytkowników, żeby umieli korzystać z produktu

**Comment by mklimek1** [comment]
Done, thank you!
