### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by martab0** [mklimek1/my-docs#11]
Bardzo potrzebny rozdział, dobrze umieszczony (tj. powinien być po Collaborate). Niestety wygląda jakby napisało go GPT 3.5. Proponuję objaśnić w 2-3 zdaniach cel testowania dokumentacji, a potem opisać, co trzeba wykonać:
- testy z wybranymi użytkownikami (jak?)
- zbieranie feedbacku od użytkowników (jak?)

**Comment by mklimek1** [comment]
corrected, thanks!
