### ISSUE TITLE
Stay on track

### ISSUE THREAD

**Issue by martab0** [mklimek1/my-docs#13]
Przeredagowałam ten rozdział :-)

As technology evolves, technical writers must stay up-to-date with industry best practices and emerging trends in software development and technical writing. Keeping up with these changes requires ongoing learning and professional development. 

One valuable resource for ongoing professional development is attending industry conferences. These events bring together experts and thought leaders in the field, providing technical writers with access to the latest trends, best practices, and emerging technologies.  
Conferences also offer opportunities to network with other professionals in the industry, which can lead to valuable connections and insights. 

> Tutaj dajesz 2-3 przykłady konferencji

In addition to conferences, technical writers can also participate in webinars and online courses that provide flexible and convenient access to new knowledge and skills.

> Tutaj dajesz 2-3 przykłady webinarów i kursów

Online forums and professional organizations are also excellent resources for staying up-to-date with industry trends and best practices, as they offer opportunities to connect with other professionals in the field and share knowledge and insights. 

> Tutaj dajesz 2-3 przykłady forów i organizacji writerskich

**Comment by mklimek1** [comment]
Dzięki, poprawione

**Comment by martab0** [comment]
Super, są już przykłady :-) Zrób z nich jeszcze klikalne odsyłacze!
