### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by martab0** [mklimek1/my-docs#2]
Na tej stronie niezbędnych jest kilka przykładowych projektów, które przyjmują pomoc dokumentalistów. Możesz je wyliczyć pod "Identify the Project" albo zrobić osobną sekcję przed "Key takeaways". Na listę dodaj projekt, do którego się przymierzałaś, i 2-3 inne, o których wiesz, że istnieją i można do nich dołączyć. Przykład z mojej strony to machinetranslate.org.

 technical writers should review and edit - tu warto uwzględnić, kto robi review: osoby z projektu open source? inni writerzy?

make it easily accessible to users - co to znaczy?

**Comment by mklimek1** [comment]
Dodałam więcej informacji i odsyłacz do sekcji 3. Find żeby nie powielać treści odnośnie przykładowych projektów dla tech writerów i dopisałam wyjaśnienie do pozostałych uwag.
