### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by martab0** [mklimek1/my-docs#3]
Na tej stronie niezbędne są konkrety:
* software documentation, technical blog posts, or video tutorials - podaj co najmniej po jednym przykładzie z każdej kategorii
* GitHub or other platforms - jakie inne platformy?
* offering other technical writing services - jakie to mogą być usługi? Np. copy edit lub review pracy innych writerów?
* Create a website or blog - podaj przynajmniej jeden przykład takiego bloga

**Comment by mklimek1** [comment]
Done, many thanks!
