### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by martab0** [mklimek1/my-docs#5]
Tutaj trzeba zacząć od informacji, że GitHub to jedno z najpopularniejszych środowisk, w jakich można włączyć się w projekty Open Source, dlatego opisujesz właśnie to. Zacznij od zakładania konta na GH - możesz odesłać do ich dokumentacji.

In summary, it is important to search for a project of one’s interest, as one of the main advantages of working for an OS software project is this flexibility and ability to fulfil oneself through the project. - warto dopisać, że osoby zarządzające projektem wprowadzą w zadania

**Comment by mklimek1** [comment]
done, thank you!

**Comment by mklimek1** [comment]
done
