### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by martab0** [mklimek1/my-docs#6]
Next, you’ll want to open the README and make sure you understand the instructions. Then, fork the repo by clicking on Fork located at the top right corner of your screen. -> 
When you contribute to a GitHub project, the most typical workflow is to fork the project. (Open the project README and make yourself familiar with the specific instructions in the very project.)  
To fork a repo, click on Fork located at the top right corner of your screen. 

Podstawowe pojęcia gita są w porządku; przyda się odsyłacz do jakiegoś podstawowego samouczka gita (tak jak zrobiłaś to dla LFS-a).

Dodaj alternatywną wersję obsługi repozytorium za pomocą aplikacji GitHub Desktop Client (możesz załatwić to przez odsyłacz do ich dokumentacji).

Informacje o LFS są w porządku, ale warto zrobić z nich osobny akapit.

Po uzupełnieniu tego rozdziału przetestuj go na jakiejś osobie nieznającej gita (np. żeby spróbowała wg tej instrukcji zrobić fork Twego repozytorium i dopisać jakieś informacje) - wtedy będziemy mieć pewność, że jest zrozumiały dla początkujących.

**Comment by mklimek1** [comment]
Done and done.
