### ISSUE TITLE
Choose

### ISSUE THREAD

**Issue by martab0** [mklimek1/my-docs#7]
Tools. What tools are the most popular among open-source technical writers? There are many tools that are popular among open-source technical writers, and the choice of tools often depends on the specific project and the preferences of the writer. Here are some of the most popular tools used by open-source technical writers: ->
There are many tools that are popular among open-source technical writers, and the choice of tools often depends on the specific project and the preferences of the writer. (usunęłam nadmiar)

Dla wszystkich narzędzi potrzebne są odsyłacze do stron i informacje, które narzędzia są płatne, a które darmowe. 
Potrzebny jest odsyłacz do strony z definicją Markdowna i z definicją gita. 
Dla gita trzeba podać przykładowe narzędzia pomocne w jego używaniu (GitHub Desktop, GitKraken lub inne).
Dla narzędzi CAT możesz podać jakieś zestawienie, np. https://geekflare.com/cat-tools/

**Comment by mklimek1** [comment]
Done, thanks!
