### ISSUE TITLE
Earn

### ISSUE THREAD

**Issue by martab0** [mklimek1/my-docs#8]
How can technical Writers make money in open-source projects? Technical writers can make money on open-source projects in several ways, including: - tylko jedno z tych zdań jest potrzebne :-)

1. Working for companies... - przykłady?
2. Working as freelance... - przykłady?
3. Contributing to open-source projects as a volunteer - to powinien być ostatni punkt, bo nie dotyczy zarabiania

Key takeaways: trzeba poprawić formatowanie i przeredagować, żeby uwzględnić, że wolontariusze jeszcze raczej nie zarabiają, tylko zbierają doświadczenia i portfolio, żeby zarabiać.

**Comment by mklimek1** [comment]
done
